# Generated by Django 4.2.19 on 2025-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='status',
            field=models.CharField(choices=[('pending', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('archived', 'Archivée')], default='pending', max_length=15),
        ),
    ]
