# Generated by Django 4.2.19 on 2025-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_servicetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='client',
            field=models.CharField(blank=True, default='Non spécifié', max_length=255),
        ),
    ]
