# Generated by Django 4.2.19 on 2025-04-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_servicetask_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostIpMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
