# Generated by Django 4.2.19 on 2025-04-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_hostipmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostipmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
