# Generated by Django 4.2.19 on 2025-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_hostcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcontact',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
